FROM openjdk:8
ADD target/InsuranceApi-InsuranceType-Service-0.0.1-SNAPSHOT.jar InsuranceApi-InsuranceType-Service.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "InsuranceApi-InsuranceType-Service.jar"]