#spring:
#  application:
#    name: eureka-server
#
#server:
#  port: 8090
#  
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    server:
#      waitTimeInMsWhenSyncEmpty: 0